spring.application.name=gateway-service
spring.main.web-application-type=reactive
server.port=8081

spring.cloud.gateway.server.webflux.routes[0].id=auth-srvice
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9000
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/register/**,/delete/**,/login,/profile/**

jwt.secret=3161413bc4f154a0d30e266d55788b16d36db7e23a0f8728ff533e04f4de73d5
