spring.application.name=gateway-service
spring.main.web-application-type=reactive
server.port=8081


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/register/**,/delete/**,/login,/profile/**

spring.cloud.gateway.server.webflux.routes[1].id=book-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/books,/books/**

spring.cloud.gateway.server.webflux.routes[2].id=borrow-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BORROW-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/borrow

jwt.secret=3161413bc4f154a0d30e266d55788b16d36db7e23a0f8728ff533e04f4de73d5


