spring.application.name=registry
server.port=8761

# Eureka server itself should not register to another Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable replication to another peer server (fixes the 8761 error)
eureka.server.peer-eureka-nodes=

# Optional but recommended for local setups
eureka.server.enable-self-preservation=true


# spring.application.name=registry
# server.port=9001
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false

